### ISSUE TITLE
running produces error

### ISSUE THREAD

**Issue by petri** [r1chardj0n3s/laughing-robot#3]
bower.py install requirejs

Traceback (most recent call last):
  File "/Users/petri/Code/koodaamo/bin/bower.py", line 7, in <module>
    from bowerlib.main import main
  File "/Users/petri/Code/koodaamo/lib/python2.7/site-packages/bowerlib/main.py", line 17, in <module>
    from bowerlib.github import GitHubRepos
  File "/Users/petri/Code/koodaamo/lib/python2.7/site-packages/bowerlib/github.py", line 1, in <module>
    from urllib import parse
ImportError: cannot import name parse

**Comment by petri** [comment]
Bah did not realize only python3 supported... my bad
